{"uuid": "41adf186-5229-44c0-b424-84ec15f66d94", "children": ["cfb6b195-f517-44bf-986a-f6d39630be2f"], "befores": [{"name": "page_on_failure", "status": "passed", "start": 1756457559647, "stop": 1756457559647}], "afters": [{"name": "page_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\tests\\conftest.py\", line 33, in page_on_failure\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1756457581298, "stop": 1756457581299}], "start": 1756457559647, "stop": 1756457581299}