{"uuid": "edc53530-e534-4494-9ea6-46ca8e5b6404", "children": ["b1b4ca1f-edc0-47b1-8ecb-c050e43b0ba8"], "befores": [{"name": "page_on_failure", "status": "passed", "start": 1756459041373, "stop": 1756459041373}], "afters": [{"name": "page_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\tests\\conftest.py\", line 33, in page_on_failure\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1756459044232, "stop": 1756459044233}], "start": 1756459041373, "stop": 1756459044233}