{"uuid": "84e0c064-58f3-42ef-8c1c-5a320eee8e30", "children": ["9b71ae5d-6f21-4d67-9065-af681f83741f"], "befores": [{"name": "page_on_failure", "status": "passed", "start": 1756459624266, "stop": 1756459624266}], "afters": [{"name": "page_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\tests\\conftest.py\", line 33, in page_on_failure\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1756459646328, "stop": 1756459646329}], "start": 1756459624266, "stop": 1756459646329}