{"uuid": "e5f64685-fbee-4bc0-b9a6-b4c0b027c5c8", "children": ["31b8a476-5b60-4b61-aa9d-20af50ed4c14"], "befores": [{"name": "page_on_failure", "status": "passed", "start": 1756459044520, "stop": 1756459044520}], "afters": [{"name": "page_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\tests\\conftest.py\", line 33, in page_on_failure\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1756459047357, "stop": 1756459047357}], "start": 1756459044520, "stop": 1756459047357}