{"uuid": "c71c5f3f-e2ba-47f3-b7b8-0248e05173ff", "children": ["03de902c-c26c-48c8-ba24-5f0f68b938b1"], "befores": [{"name": "page_on_failure", "status": "passed", "start": 1756459668849, "stop": 1756459668849}], "afters": [{"name": "page_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\DELL\\pytest-sample\\tests\\conftest.py\", line 33, in page_on_failure\n    if request.node.rep_call.failed:\n       ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1756459690990, "stop": 1756459690991}], "start": 1756459668849, "stop": 1756459690991}